### ISSUE TITLE
UI submit button is not working/some errors when using CLI

### ISSUE THREAD

**Issue by bbernardSMA** [SMATechnologies/opcon-selfservice-manager-powershell#1]
Hello,

I took time to try and test this feature via Powershell script to import export Self Service button.

Unfortunately I was not able to use the UI or the CLI.

For the UI when we start the OpConsole.ps1 we get the error below :
![2021-06-28_17h25_01](https://user-images.githubusercontent.com/86614977/123664305-80c30f00-d837-11eb-8de5-7dbda33946db.png)
![2021-06-28_17h25_26](https://user-images.githubusercontent.com/86614977/123664343-8c163a80-d837-11eb-9691-5ebcdaa7c3ff.png)

So I fixed the script location in the ps1 file and the UI was able to start, then I use F2 to browse the menu, and I tried to add a new environement :
![2021-06-28_17h29_02](https://user-images.githubusercontent.com/86614977/123664542-b5cf6180-d837-11eb-98a7-e1df696bcc16.png)

Unfortunately when we click on the submit button nothing happen, I didn't find any log to explain why the button doesn't respond.

So then I tried the CLI command and I got this error :
![2021-06-28_17h32_22](https://user-images.githubusercontent.com/86614977/123664752-ec0ce100-d837-11eb-8900-2d03ed78e4d9.png)

It seems the name the called function is not correct :
![2021-06-28_17h32_59](https://user-images.githubusercontent.com/86614977/123664823-00e97480-d838-11eb-82fe-f6585e4240c4.png)
![2021-06-28_17h34_17](https://user-images.githubusercontent.com/86614977/123664828-021aa180-d838-11eb-9962-4188d13dcc1c.png)

Could you please have a look on it ?

I have a customer who would like to this working for SS import export has they have several buttons they like to avoid to copy manually from the test to production.

Thanks
Benjamin

**Comment by opconWizard** [comment]
@bbernardSMA I think its not finding the module files correctly.  The "OpConsole_CLI_Module.psm1" which is part of this repository should be in the **same** directory as the OpConsole.ps1.  

The OpConModule.psm1 (which can be used in other PS scripts as well) could be stored anywhere but would need to be specified on the command line with "-OpConModule" when executing OpConsole.ps1 (it sounds like you figured that out).  I'll update the documentation to reflect that.

**Comment by bbernardSMA** [comment]
Hello,

I'm not sure it's only a problem on the psm1 location, as on the screenshot below still get errors

![2021-06-29_14h46_18](https://user-images.githubusercontent.com/86614977/123918935-ac074480-d984-11eb-8971-4dbbb8a17379.png)

here I specify the location by the -OpConModule parameter and I'm not able to have it working moreover I tried to fix the red message but without success like you can on this two attempt above.

For the UI I'm still not able to add a new environment I don't know why the submit button doesn't work.

For your information, all scripts are extracted in the same repository.

Thanks
Benjamin

**Comment by opconWizard** [comment]
@bbernardSMA I did some testing and I think the problem is you are specifying a user/password AND a API Token and you only need to supply 1 of those.  Otherwise sometimes it appears to be doing nothing after submit, when its really trying to connect to the OpCon environment and cannot (perhaps https instead of http, typo etc).

Can you try with just a password or just the API token?

**Comment by bbernardSMA** [comment]
It works better now, however when I try to import a button I get these errors below, just before it told me "Roles will be set to ocadm" and I selected the target environment.

[91mOperationStopped: [0mC:\Users\Administrateur\Desktop\ss\OpConsole_Self_Service_Module.psm1:369
[96mLine |
[96m 369 | [0m             [96m[Terminal.Gui.MessageBox]::Query("Import complete", ("Imp[0m .
[96m     | [91m             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mIndex was outside the bounds of the array.
[0m
[91mSetValueInvocationException: [0mC:\Users\Administrateur\Desktop\ss\OpConsole_Self_Service_Module.psm1:305
[96mLine |
[96m 305 | [0m             [96m$sourceButton.roles = @(@{ "id" = 0;"name"="ocadm"})[0m
[96m     | [91m             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mException setting "roles": "The property 'roles' cannot be found on this object. Verify that the
[96m     | [91mproperty exists and can be set."
[0m
[
  {
    "resource": "serviceRequest",
    "name": "roles",
    "code": 5002,
    "message": "No roles specified for the service request."
  }
]
Response status code does not indicate success: 400 (Bad Request).

Thanks
Benjamin

**Comment by opconWizard** [comment]
@bbernardSMA I found the bug for this.  It had to do with how the API works, if you pull all the buttons at once it does not return the "roles" for each.  I fixed the bug and made a few other adjustment, try again and let me know how it goes.

[https://github.com/smatechnologies/opcon-selfservice-manager-powershell/releases/tag/v1.7](url)

**Comment by opconWizard** [comment]
@bbernardSMA were you able to test the changes?

**Comment by bbernardSMA** [comment]
Hello,

I realized a new test, but unfortunately on my side I wasn't able to have my import working :
![2021-07-19_15h13_31](https://user-images.githubusercontent.com/86614977/126169074-91a04053-38e2-4368-acca-9b12f7f30591.png)
![2021-07-19_15h18_06](https://user-images.githubusercontent.com/86614977/126169152-b59fa674-9687-47d5-9832-f4ddf0932fd6.png)

Perhaps I missed something, what I did : I exported my buttons in json file, then I deleted one button on my solution manager, and I tried to import the deleted button from your tool by the import function.

Thanks
Benjamin

**Comment by opconWizard** [comment]
@bbernardSMA  The program is not setup to overwrite buttons with the same name, you would have to change the names to have the import of existing ones work.  I did this as a safety configuration but could have an option for that in the future (to overwrite).

Did the issue for this get resolved?  You can open a new issue for the new test if you try again and have issues.

**Comment by bbernardSMA** [comment]
Hello,

We are good, you can close this issue.

Thanks
Benjamin
